# Generates proxied/version.h with the current git version string.
# Usage: cmake -P generate_version.cmake <output_file> <source_dir>

set(VERSION_FILE "${CMAKE_ARGV3}")
set(SOURCE_DIR "${CMAKE_ARGV4}")

find_package(Git QUIET)

set(VERSION "v0.0.0-unknown")

if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
    # 1) If the current commit is exactly on a tag, use that tag as the version.
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --exact-match
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE EXACT_TAG
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )

    if(EXACT_TAG)
        set(VERSION "${EXACT_TAG}")
    else()
        # 2) Otherwise fall back to the latest tag plus the commit id.
        execute_process(
            COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE LATEST_TAG
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        if(NOT LATEST_TAG)
            set(LATEST_TAG "v0.0.0")
        endif()

        execute_process(
            COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE COMMIT_ID
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        if(NOT COMMIT_ID)
            set(COMMIT_ID "unknown")
        endif()

        set(VERSION "${LATEST_TAG}-${COMMIT_ID}")

        # 3) Mark dirty only when there are uncommitted (tracked) changes.
        execute_process(
            COMMAND ${GIT_EXECUTABLE} diff-index --quiet HEAD --
            WORKING_DIRECTORY "${SOURCE_DIR}"
            RESULT_VARIABLE DIRTY_RESULT
            ERROR_QUIET
        )
        if(NOT DIRTY_RESULT EQUAL 0)
            set(VERSION "${VERSION}-dirty")
        endif()
    endif()
endif()

set(CONTENT "// Auto-generated by generate_version.cmake. Do not edit.\n#pragma once\n#define PROXIED_VERSION L\"${VERSION}\"\n")
file(WRITE "${VERSION_FILE}" "${CONTENT}")
